### PR TITLE
fix: update players

### LINKED ISSUE #44: Fix duplicate questions_correct

### PR DESCRIPTION
**Pull request by kohljd**
prevent duplicates in questions_correct array
base answers_correct on question_correct array size update tests to reflect changes

## Type of change
- [ ] New feature
- [x] Bug Fix
- [ ] Refactor
- [ ] Styling
- [ ] Documentation
- [ ] Other:

## Description

Players Controller
- search for player via game_id and id to ensure correct player record updated
- player updates are now saved

Player Model
- Add `.uniq` to prevent duplicate questions
- `answers_correct` based on` questions_correct` array size to prevent change if the same question number is sent twice for a player update
- question enters array as a string to allow for consistency in API response ( `["1", "2"]` instead of `["1", 2]` )

## Issue(s):
closes #44 

## Necessary checkmarks:
- [x] All Tests are Passing
- [x] The code will run locally
- [x] Unnecessary comments removed
- [x] Test coverage 100%

*What tests are still needed if coverage not 100%*

## Any Outstanding Issues/Problems?
- [x] My code is wonderful, no issues here!
- [ ] Yeah, see additional words below

### CODE REVIEW

File: spec/models/player_spec.rb [hunk 1]
```diff
@@ -20,31 +20,30 @@
...
-        "options"=>["Umbrella", "Diamonds", "Love on the Brain", "Pon de Replay"]
-      }
-
-      question_1 = Question.new(data)
-      question_2 = Question.new(data)
-
-      @game = Game.create!({topic: "Music Trivia", number_of_questions: 2, number_of_players: 1})
-
-      @player = Player.create!({display_name: "OP", game_id: @game.id})
+      game = create(:game)
```
Comment (laurarvegav) [inline spec/models/player_spec.rb:23]: Of course!! The factories.... Thank you this is So much better

**Review by laurarvegav — APPROVED** [review]
As always, love the thorough testing and don't have any changes to suggest.
