### PR TITLE
Fix/timeout

### LINKED ISSUE #67: Fix 503 error
503 error code sometimes thrown when creating a trivia game. Cause seems to be request to questions microservice timing out due to the microservice server on render having to startup.

## Heroku Details
Request Timeouts: There has been 1 timeout error in the current period. Try investigating slow requests, adding more dynos or running more processes per dyno.

Image

## Example Response
Status Code: 
```http
503 (Error: Service Unavailable)
```

Response Body:
```html
<!DOCTYPE html>
	<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>
	</html>
```

Response Headers:
```
 cache-control: no-cache,no-store 
 connection: keep-alive 
 content-length: 506 
 content-type: text/html; charset=utf-8 
 date: Fri,31 May 2024 15:03:32 GMT 
 nel: {"report_to":"heroku-nel","max_age":3600,"success_fraction":0.005,"failure_fraction":0.05,"response_headers":["Via"]} 
 report-to: {"group":"heroku-nel","max_age":3600,"endpoints":[{"url":"https://nel.heroku.com/reports?ts=1717167782&sid=929419e7-33ea-4e2f-85f0-7d8b7cd5cbd6&s=z27hLRIDVjmmQOXwh5Mn9XGvt513gYSoYgK7zsi7xJg%3D"}]} 
 reporting-endpoints: heroku-nel=https://nel.heroku.com/reports?ts=1717167782&sid=929419e7-33ea-4e2f-85f0-7d8b7cd5cbd6&s=z27hLRIDVjmmQOXwh5Mn9XGvt513gYSoYgK7zsi7xJg%3D 
 server: Cowboy
```

### PR DESCRIPTION
**Pull request by kohljd**
## Type of change
- [ ] New feature
- [x] Bug Fix
- [ ] Refactor
- [ ] Styling
- [ ] Documentation
- [ ] Other:

## Description

If the API request to the questions microservice fails due to timeout error, Faraday will retry the API call up to 2 times at a 2 second interval.

Note: The POST request's body had to be manually converted to JSON for tests to pass. Doesn't appear to cause issues 

Faraday gem's [middleware docs](https://lostisland.github.io/faraday/#/middleware/index?id=middleware:~:text=The%20Awesome%20Faraday%20project%20has%20a%20complete%20list%20of%20useful%2C%20well%2Dmaintained%20Faraday%20middleware.%20Middleware%20is%20often%20provided%20by%20external%20gems%2C%20like%20the%20faraday%2Dretry%20gem.)
Faraday-retry gem's [GitHub](https://github.com/lostisland/faraday-retry)

## Issue(s):
closes #67 

## Necessary checkmarks:
- [x] All Tests are Passing
- [x] The code will run locally
- [x] Unnecessary comments removed
- [x] Test coverage 100%

## Any Outstanding Issues/Problems?
- [x] My code is wonderful, no issues here!
- [ ] Yeah, see additional words below

### CODE REVIEW

File: app/services/question_service.rb [hunk 1]
```diff
@@ -1,15 +1,19 @@
...
-    response = conn.post(url, params)
+    response = conn.post(url, JSON.generate(params))
     @parsed_json = JSON.parse(response.body, symbolize_names: true)
   end
 
   def self.conn
-    Faraday.new(url: "https://brain-defrost-be-questions.onrender.com")
+    Faraday.new(url: "https://brain-defrost-be-questions.onrender.com") do |faraday|
+      faraday.request :retry, max: 2, interval: 2, exceptions: [Faraday::TimeoutError]
+    end
```
Comment (laurarvegav) [inline app/services/question_service.rb:17]: sounds great!!!!

**Review by laurarvegav — APPROVED** [review]
